services:
  # image project
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - redis
      - db
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel

  # db mysql
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel_docker}    # Tên database sẽ được tạo tự động
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}    # Mật khẩu cho user root
      MYSQL_USER: ${DB_USERNAME:-username}              # Tên người dùng sẽ được tạo
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}              # Mật khẩu cho người dùng sẽ được tạo
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3388:3306"
    networks:
      - laravel

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root} # Root password for phpMyAdmin
    networks:
      - laravel

  # redis
  redis:
    image: redis:latest
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
